configs:
  telegraf:
    content: |
      [global_tags]
        env = "demo"
      [agent]
        interval = "10s"
        round_interval = true
        metric_batch_size = 1000
        metric_buffer_limit = 10000
        collection_jitter = "0s"
        flush_interval = "10s"
        flush_jitter = "0s"
        precision = "0s"
      [[outputs.nats]]
        servers = ["nats://nats:4222"]
        name = "telegraf"
        subject = "telegraf"
        data_format = "cloudevents"
        cloudevents_version = "1.0"
        cloudevents_source = "telegraf"
        cloudevents_event_type = "com.github.mwmahlberg.se-monitoringevents-454044.telegraf"
        cloudevents_event_time = "creation"
        [outputs.nats.jetstream]
          name = "ping-results"
      [[inputs.ping]]
        # The double dollar sign is required to escape the variable in docker-compose
        # and to pass it to the telegraf container as $PING_TARGETS
        urls = [$${PING_TARGETS}]
        method = "native"

services:
  nats:
    image: nats:2-alpine
    command: "-m 8222 -n mq --js"
    ports:
      - 4222:4222
      - 8222:8222
    healthcheck:
      test: [ "CMD", "wget", "http://localhost:8222/healthz", "-q", "-S", "-O", "-" ]
      interval: 10s
      timeout: 1s
      retries: 5
      start_period: 30s
  telegraf:
    image: telegraf:1.34-alpine
    environment:
      - HOSTNAME=telegraf
      - PING_TARGETS="telegraf","nats"
    ports:
      - 9273:9273
    restart: always
    depends_on:
      nats:
        condition: service_healthy
    cap_add:
      # Required in podman
      - NET_RAW
    configs:
      - source: telegraf
        target: /etc/telegraf/telegraf.conf

  processor:
    image: mwmahlberg/se-monitoringevents-454044-processor:latest
    depends_on:
      nats:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - PROCESSOR_NATS_HOST=nats:4222
      - PROCESSOR_NATS_STREAM_NAME=ping-results
      - PROCESSOR_LOG_LEVEL=debug
