apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  strategy:
    type:  Recreate
  template:
    metadata:
      labels:
        app: snmp-exporter
        editor: vscode
    spec:
      containers:
      - name: name
        image: prom/snmp-exporter:v0.29.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 9116
          name: snmp-exporter
