apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobsink-demo
  namespace: knative-eventing
spec:
  rules:
  - host: "jobsink-demo.127-0-0-1.sslip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: job-sink
            port:
              number: 80