apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/knative/serving/releases/download/knative-v1.18.0/serving-core.yaml
  - https://github.com/knative/net-kourier/releases/download/knative-v1.18.0/kourier.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.18.0/serving-default-domain.yaml
patches:
  - target:
      kind: ConfigMap
      name: config-network
      namespace: knative-serving
    patch: |-
      - op: add
        path: /data
        value:
          ingress-class: kourier.ingress.networking.knative.dev

